config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  resources :lists do
    resources :items
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'lists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :description, presence: true
  STATUS = {
    incomplete: 0,
    complete: 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  # PATCH - /lists/:list_id/items/:id
  def update
    @list = List.find_by(id: params[:list_id])
    @item = @list.items.find_by(id: params[:id])
    @item.update(item_params)

    redirect_to list_path(@list)
  end

  # DELETE - /lists/:list_id/items/:id
  def destroy
    @list = List.find_by(id: params[:list_id])
    @item = @list.items.find_by(id: params[:id])
    @item.destroy

    redirect_to list_path(@list)
  end

  private
  def item_params
    params.require(:item).permit(:description, :status)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to root_path
    else
      @lists = List.all
      render :index
    end
  end

  def show
    @list = List.find(params[:id])
    @item = Item.new
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def form_for_item_status(item)
    form_for([@list, item]) do |f|
      f.check_box :status, class: "toggle", checked: item.complete?
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_item_li.html.erb
<li class="<%= li_class_for_item(item) %>">
  <div class="view">
    <%= form_for_item_status(item) %>
    <label><%= item.description %></label>

    <%= button_to "x", list_item_path(item.list, item), method: "delete", class: "destroy" %>

  </div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMvcLv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>

  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
	<header class="header">
		<h1>Your Lists</h1>
    <%= form_for(@list) do |f| %>
      <%= f.text_field :name, :class => "new-todo", placeholder: (@list.errors.full_messages_for(:name).first || "Create a new list" ) %>
    <% end %>
	</header>

	<section class="main">
		<ul class="todo-list">
      <% @lists.each do |list| %>
        <li>
          <div class="view">
            <label><%= link_to list.name, list_path(list) %></label>
          </div>
        </li>
      <% end %>
    </ul>
	</section>

	<footer class="footer" style="display: block;">
	</footer>
</section>

app/views/lists/show.html.erb
<section class="todoapp">
	<header class="header">
		<h1><%= @list.name %></h1>
		<%= form_for([@list, @item]) do |f| %>
      <%= f.text_field :description, :class => "new-todo", placeholder: (@item.errors.full_messages_for(:description).first || "Create a new todo" )  %>
			<%= f.submit style: "display: none" %>
    <% end %>
	</header>

	<section class="main">
		<input class="toggle-all" type="checkbox"></input>
		<label for="toggle-all">Mark all as complete</label>
		<ul class="todo-list">
			<%= render collection: @list.items, partial: 'items/item_li', as: :item %>
    </ul>
	</section>

	<footer class="footer" style="display: block;">
	</footer>
</section>